from pathlib import Path

files = [
    Path(r'c:\Users\Phale\Documents\GitHub\ehoser-store-co\public\app.js'),
    Path(r'c:\Users\Phale\Documents\GitHub\ehoser-store-co\server-supabase.js'),
]

replacements = {
    'â”€': '─',
    'â€“': '–',
    'â€”': '—',
    'â€¦': '…',
    'â€˜': '‘',
    'â€™': '’',
    'â€œ': '“',
    'â€': '”',
    'â€¢': '•',
    'â†': '→',
    'â€º': '»',
    'â€¹': '«',
    'â‚¬': '€',
    'Ã¼': 'ü',
    'Ã¶': 'ö',
    'Ã¤': 'ä',
    'ÃŸ': 'ß',
    'Ã–': 'Ö',
    'Ãœ': 'Ü',
    'Ã„': 'Ä',
    'Ã¡': 'á',
    'Ã©': 'é',
    'Ã³': 'ó',
    'Ãº': 'ú',
    'Ã±': 'ñ',
    'Ã­': 'í',
    'Ã§': 'ç',
    'Ã¹': 'ù',
    'Â©': '©',
    'Â°': '°',
    'ðŸš€': '🚀',
    'ðŸ“Š': '📨',
    'ðŸ™ˆ': '🙈',
    'ðŸš«': '🚫',
    'ðŸ‘‹': '👋',
    'fÃ¼r': 'für',
    'Ã¼ber': 'über',
    'Ã¶ber': 'öber',
    'Ã¤ngste': 'Ängste',
    'Ã¼bersprungen': 'übersprungen',
    'Ã¼berprÃ¼ft': 'überprüft',
    'PrÃ¼fen': 'Prüfen',
    'VerfÃ¼gbar': 'Verfügbar',
    'UngÃ¼ltig': 'Ungültig',
    'gelÃ¶scht': 'gelöscht',
    'geÃ¤ndert': 'geändert',
    'wÃ¼rde': 'würde',
    'gefÃ¼hl': 'gefühl',
    'fÃ¼hlst': 'fühlst',
    'SchlieÃŸen': 'Schließen',
    'UnterstÃ¼tzung': 'Unterstützung',
    'erfÃ¼llt': 'erfüllt',
    'Pro enthaelt': 'Pro enthält',
    'enthaelt': 'enthält',
    'KI nicht verfÃ¼gbar': 'KI nicht verfügbar',
    'Verifikation Ã¼bersprungen': 'Verifikation übersprungen',
    'einfacher fÃ¼r dich': 'einfacher für dich',
    'fehlgeschlagen â€“ kein Dienst verfÃ¼gbar': 'fehlgeschlagen – kein Dienst verfügbar',
    'Kein Public Key gefunden â€“ Nutzer muss Chat einmal geÃ¶ffnet haben': 'Kein Public Key gefunden – Nutzer muss Chat einmal geöffnet haben',
    'Chat API (E2E verschlÃ¼sselt)': 'Chat API (E2E verschlüsselt)',
    'Anhang-Button nur fÃ¼r PRO sichtbar': 'Anhang-Button nur für PRO sichtbar',
    'Spiele werden geladenâ€¦': 'Spiele werden geladen…',
    'Multer â€“ memory storage fÃ¼r Supabase-Upload': 'Multer – memory storage für Supabase-Upload',
    'Google-Token ungÃ¼ltig': 'Google-Token ungültig',
    'Datenbank-Tabellen Ã¼berprÃ¼ft/erstellt.': 'Datenbank-Tabellen überprüft/erstellt.',
    'Kein Upload-Bucket verfÃ¼gbar': 'Kein Upload-Bucket verfügbar',
    'keine Dienst verfÃ¼gbar': 'kein Dienst verfügbar',
    'Nutzer konnte nicht gelÃ¶scht werden': 'Nutzer konnte nicht gelöscht werden',
    'Bitte alle Pflichtfelder ausfÃ¼llen.': 'Bitte alle Pflichtfelder ausfüllen.',
    'Vollzugang': 'Vollzugang',
    'â€': '…',
}

for path in files:
    text = path.read_text(encoding='utf-8', errors='surrogateescape')
    original = text
    for old, new in replacements.items():
        text = text.replace(old, new)
    if text != original:
        path.write_text(text, encoding='utf-8', errors='surrogateescape')
        print(f'updated {path.name}')
